#!/bin/sh

# Update GeoIP database

BASE_GEOIP_DBS_URL=

if [ -z "$BASE_GEOIP_DBS_URL" ]; then
    exit 0
fi

tmp_file="$(mktemp)"
if curl -sk "${BASE_GEOIP_DBS_URL}/GeoLite2-Country.mmdb" -o "$tmp_file"; then
    mkdir -p /usr/share/GeoIP
    rm -f "/usr/share/GeoIP/GeoLite2-Country.mmdb"
    mv "$tmp_file" "/usr/share/GeoIP/GeoLite2-Country.mmdb"
    chown -R root:root /usr/share/GeoIP
    chmod 755 /usr/share/GeoIP
    chmod 644 "/usr/share/GeoIP/GeoLite2-Country.mmdb"
else
    rm -f "$tmp_file"
    exit 1
fi

exit 0
